//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolFuncionalities
    {
        public short Id { get; set; }
        public string Description { get; set; }
        public string Controller { get; set; }
        public bool State { get; set; }
        public Nullable<short> RolId { get; set; }
    
        public virtual Rols Rols { get; set; }
    }
}
